version: '3.7'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always


volumes:
  static_volume:
  media_volume:
